# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-07 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('selected_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OptionToShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
                ('order_in_steps', models.IntegerField()),
                ('next_step_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionToShowResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
                ('option_id', models.IntegerField(blank=True, null=True)),
                ('next_step_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('file', models.ImageField(upload_to=webpage.models.workflow_result_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_username', models.CharField(blank=True, max_length=255)),
                ('gmail_username', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('institucion', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(editable=False)),
                ('participants', models.ManyToManyField(through='webpage.ParticipantsGroup', to='webpage.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RouteInformationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bearing', models.DecimalField(decimal_places=4, max_digits=10)),
                ('elapsed_realtime_nanos', models.BigIntegerField()),
                ('fields_mask', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('provider', models.TextField(max_length=500)),
                ('speed', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('native_ptr', models.BigIntegerField(blank=True, null=True)),
                ('native_size', models.IntegerField(blank=True, null=True)),
                ('owns_native_parcel_object', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('SelectOneStepResult', 'SelectOneStepResult'), ('SelectMultipleStepResult', 'SelectMultipleStepResult')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SoundRecordStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=webpage.models.workflow_result_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('DateStep', 'DateStep'), ('TextStep', 'TextStep'), ('InformationStep', 'InformationStep'), ('PhotoStep', 'PhotoStep'), ('LocationStep', 'LocationStep'), ('SelectOneStep', 'SelectOneStep'), ('SelectMultipleStep', 'SelectMultipleStep'), ('TimeStep', 'TimeStep'), ('RouteStep', 'RouteStep'), ('SoundRecordStep', 'SoundRecordStep')], max_length=30)),
                ('next_step_id', models.IntegerField(blank=True, null=True)),
                ('step_id', models.IntegerField()),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
                ('sample_text', models.TextField(blank=True, max_length=500)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('optional', models.NullBooleanField()),
                ('input_type', models.CharField(blank=True, choices=[('number', 'number'), ('text', 'text'), ('decimal', 'decimal')], max_length=1)),
                ('title', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TextStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('inserted_text', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('selected_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='webpage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('sent', models.NullBooleanField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.Profile')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_results', to='webpage.Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='timestepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_step_results', to='webpage.WorkflowResult'),
        ),
        migrations.AddField(
            model_name='textstepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_step_results', to='webpage.WorkflowResult'),
        ),
        migrations.AddField(
            model_name='step',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='webpage.Workflow'),
        ),
        migrations.AddField(
            model_name='soundrecordstepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_step_results', to='webpage.WorkflowResult'),
        ),
        migrations.AddField(
            model_name='selectstepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_step_results', to='webpage.WorkflowResult'),
        ),
        migrations.AddField(
            model_name='routestepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_step_results', to='webpage.WorkflowResult'),
        ),
        migrations.AddField(
            model_name='routeinformationresult',
            name='route_step_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_information_results', to='webpage.RouteStepResult'),
        ),
        migrations.AddField(
            model_name='photostepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_step_results', to='webpage.WorkflowResult'),
        ),
        migrations.AddField(
            model_name='participantsgroup',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Profile'),
        ),
        migrations.AddField(
            model_name='participantsgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Project'),
        ),
        migrations.AddField(
            model_name='optiontoshowresult',
            name='select_step_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_results', to='webpage.SelectStepResult'),
        ),
        migrations.AddField(
            model_name='optiontoshow',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_to_show', to='webpage.Step'),
        ),
        migrations.AddField(
            model_name='locationstepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_step_results', to='webpage.WorkflowResult'),
        ),
        migrations.AddField(
            model_name='datestepresult',
            name='workflow_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_step_results', to='webpage.WorkflowResult'),
        ),
    ]
