# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='participantsgroup',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
