# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-27 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datestepresult',
            old_name='selected_time',
            new_name='selected_date',
        ),
    ]
