# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-25 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webpage.Project'),
            preserve_default=False,
        ),
    ]
