# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-12-14 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiontoshow',
            old_name='order_in_steps',
            new_name='option_id',
        ),
    ]
