# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-06 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='input_type',
            field=models.CharField(blank=True, choices=[('number', 'number'), ('text', 'text'), ('decimal', 'decimal')], max_length=1),
        ),
    ]
