# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='next_step',
        ),
        migrations.AddField(
            model_name='step',
            name='order_in_workflow',
            field=models.IntegerField(null=True),
        ),
    ]
