# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-13 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_step_next_step_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='next_step_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
