# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-27 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_workflow_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
