# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-13 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20180513_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontoshow',
            name='next_step_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
