# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-19 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_optiontoshow_next_step_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='image_to_overlay',
            new_name='instructions_to_show',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='instruct_to_show',
            new_name='photo_instructions',
        ),
        migrations.AddField(
            model_name='step',
            name='interval',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='map_zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('DateStep', 'DateStep'), ('TextStep', 'TextStep'), ('InformationStep', 'InformationStep'), ('PhotoStep', 'PhotoStep'), ('LocationStep', 'LocationStep'), ('SelectOneStep', 'SelectOneStep'), ('SelectMultipleStep', 'SelectMultipleStep'), ('TimeStep', 'TimeStep'), ('RouteStep', 'RouteStep'), ('SoundRecordStep', 'SoundRecordStep')], max_length=30),
        ),
    ]
