# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-12 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_project_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InformationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LocationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleSelectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleSelectStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct_to_show', models.TextField(blank=True, max_length=500)),
                ('image_to_overlay', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SelectOneOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SelectOneStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(blank=True, max_length=30)),
                ('next_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step')),
            ],
        ),
        migrations.CreateModel(
            name='TextStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
                ('sample_test', models.TextField(blank=True, max_length=500)),
                ('max_length', models.IntegerField()),
                ('inputy_type', models.CharField(choices=[('N', 'number'), ('M', 'text'), ('L', 'decimal')], max_length=1)),
                ('optional', models.BooleanField(default=False)),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='selectonestep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step'),
        ),
        migrations.AddField(
            model_name='selectoneoption',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.SelectOneStep'),
        ),
        migrations.AddField(
            model_name='photostep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step'),
        ),
        migrations.AddField(
            model_name='multipleselectstep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step'),
        ),
        migrations.AddField(
            model_name='multipleselectoption',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.MultipleSelectStep'),
        ),
        migrations.AddField(
            model_name='locationstep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step'),
        ),
        migrations.AddField(
            model_name='informationstep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step'),
        ),
        migrations.AddField(
            model_name='datestep',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Step'),
        ),
    ]
