# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontoshow',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_to_show', to='webpage.Step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='webpage.Workflow'),
        ),
    ]
