# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_auto_20180519_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
