# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
