# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-03 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_project_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='sample_test',
            new_name='sample_text',
        ),
        migrations.RemoveField(
            model_name='step',
            name='instructions_to_show',
        ),
        migrations.RemoveField(
            model_name='step',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='step',
            name='map_zoom',
        ),
        migrations.RemoveField(
            model_name='step',
            name='photo_instructions',
        ),
    ]
