# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-24 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_auto_20180603_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('selected_time', models.DateTimeField()),
                ('workflow_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='LocationStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.BigIntegerField(blank=True, null=True)),
                ('longitude', models.BigIntegerField(blank=True, null=True)),
                ('workflow_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='OptionToShowResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_show', models.TextField(blank=True, max_length=500)),
                ('option_id', models.IntegerField(blank=True, null=True)),
                ('next_step_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PhotoStepResult', 'PhotoStepResult'), ('SoundRecordStepResult', 'SoundRecordStepResult')], max_length=30)),
                ('resource_path', models.TextField(blank=True, max_length=500)),
                ('workflow_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SelectStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('select_type', models.CharField(choices=[('SelectOneStepResult', 'SelectOneStepResult'), ('SelectMultipleStepResult', 'SelectMultipleStepResult')], max_length=30)),
                ('workflow_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TextStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('inserted_text', models.TextField(blank=True, max_length=500)),
                ('workflow_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_date', models.DateTimeField()),
                ('end_time_date', models.DateTimeField()),
                ('sent', models.NullBooleanField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.Project')),
            ],
        ),
        migrations.AddField(
            model_name='optiontoshowresult',
            name='select_step_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.SelectStepResult'),
        ),
    ]
