# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-24 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_auto_20180624_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowresult',
            old_name='end_time_date',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='workflowresult',
            old_name='start_time_date',
            new_name='start_date_time',
        ),
    ]
