# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_auto_20180624_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datestepresult',
            name='workflow_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult'),
        ),
        migrations.AlterField(
            model_name='locationstepresult',
            name='workflow_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult'),
        ),
        migrations.AlterField(
            model_name='resourcestepresult',
            name='workflow_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult'),
        ),
        migrations.AlterField(
            model_name='selectstepresult',
            name='workflow_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult'),
        ),
        migrations.AlterField(
            model_name='textstepresult',
            name='workflow_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult'),
        ),
    ]
