# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-24 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_auto_20180624_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowresult',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowresult',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
