# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-26 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_auto_20180624_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowresult',
            name='project',
        ),
        migrations.AddField(
            model_name='workflowresult',
            name='workflow',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='webpage.Workflow'),
            preserve_default=False,
        ),
    ]
