# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_auto_20180628_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationstepresult',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='locationstepresult',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
