# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-28 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_auto_20180628_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationstepresult',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='locationstepresult',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
