# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-30 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0017_auto_20180628_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectstepresult',
            old_name='select_type',
            new_name='type',
        ),
    ]
