# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-03 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_auto_20180701_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('file', models.ImageField(upload_to=webpage.models.workflow_result_directory_path)),
                ('workflow_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult')),
            ],
        ),
        migrations.CreateModel(
            name='SoundRecordStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=webpage.models.workflow_result_directory_path)),
                ('workflow_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult')),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcestepresult',
            name='workflow_result',
        ),
        migrations.DeleteModel(
            name='ResourceStepResult',
        ),
    ]
