# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-03 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0021_auto_20180703_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateStepResult',
            new_name='TimeStepResult',
        ),
    ]
