# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0022_auto_20180703_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteInformationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acurracy', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('bearing', models.DecimalField(decimal_places=7, max_digits=10)),
                ('elapsed_realtime_nanos', models.BigIntegerField()),
                ('field_mask', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('provider', models.TextField(max_length=500)),
                ('speed', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('flags', models.IntegerField(blank=True, null=True)),
                ('native_ptr', models.BigIntegerField(blank=True, null=True)),
                ('native_size', models.IntegerField(blank=True, null=True)),
                ('owns_native_parcel_object', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('workflow_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.WorkflowResult')),
            ],
        ),
        migrations.AddField(
            model_name='routeinformationresult',
            name='route_step_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.RouteStepResult'),
        ),
    ]
