# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-09 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0025_auto_20180709_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeinformationresult',
            old_name='field_mask',
            new_name='fields_mask',
        ),
    ]
