# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-09 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0027_auto_20180709_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinformationresult',
            name='accuracy',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='routeinformationresult',
            name='altitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='routeinformationresult',
            name='bearing',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
