# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-08-26 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0028_auto_20180709_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.Profile'),
        ),
    ]
